package output

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"time"
)

// ReportData holds all data needed to generate a report.
type ReportData struct {
	Title       string
	Workspace   string
	GeneratedAt time.Time
	Findings    []ReportFinding
	Resources   map[string]int
	GraphStats  map[string]int
}

// ReportFinding is a finding formatted for reports.
type ReportFinding struct {
	Module      string
	Severity    string
	Title       string
	Description string
	Resource    string
	Project     string
}

// GenerateJSON writes a JSON report to the given path.
func GenerateJSON(data *ReportData, path string) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	enc := json.NewEncoder(f)
	enc.SetIndent("", "  ")
	return enc.Encode(data)
}

// GenerateMarkdown writes a Markdown report to the given path.
func GenerateMarkdown(data *ReportData, path string) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	w := func(format string, args ...any) {
		fmt.Fprintf(f, format+"\n", args...)
	}

	w("# %s", data.Title)
	w("")
	w("**Workspace:** %s", data.Workspace)
	w("**Generated:** %s", data.GeneratedAt.Format("2006-01-02 15:04:05"))
	w("")

	// Executive summary.
	w("## Executive Summary")
	w("")
	sevCounts := make(map[string]int)
	for _, finding := range data.Findings {
		sevCounts[finding.Severity]++
	}
	w("| Severity | Count |")
	w("|----------|-------|")
	for _, sev := range []string{"CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"} {
		if c, ok := sevCounts[sev]; ok {
			w("| %s | %d |", sev, c)
		}
	}
	w("")

	// Resource inventory.
	if len(data.Resources) > 0 {
		w("## Resource Inventory")
		w("")
		w("| Service | Count |")
		w("|---------|-------|")
		for svc, count := range data.Resources {
			w("| %s | %d |", svc, count)
		}
		w("")
	}

	// Findings detail.
	w("## Findings")
	w("")
	for _, sev := range []string{"CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"} {
		findings := filterBySeverity(data.Findings, sev)
		if len(findings) == 0 {
			continue
		}
		w("### %s", sev)
		w("")
		for _, finding := range findings {
			w("#### %s", finding.Title)
			w("")
			w("- **Module:** `%s`", finding.Module)
			w("- **Resource:** `%s`", finding.Resource)
			w("- **Project:** %s", finding.Project)
			w("- **Description:** %s", finding.Description)
			w("")
		}
	}

	// Attack graph stats.
	if len(data.GraphStats) > 0 {
		w("## Attack Graph")
		w("")
		w("| Metric | Value |")
		w("|--------|-------|")
		for k, v := range data.GraphStats {
			label := strings.ReplaceAll(k, "_", " ")
			w("| %s | %d |", label, v)
		}
		w("")
	}

	w("---")
	w("*Generated by Nimbus GCP Pentesting Framework*")

	return nil
}

func filterBySeverity(findings []ReportFinding, severity string) []ReportFinding {
	var filtered []ReportFinding
	for _, f := range findings {
		if f.Severity == severity {
			filtered = append(filtered, f)
		}
	}
	return filtered
}
